### ISSUE TITLE
GPG key checking disabled for RPMs

### ISSUE THREAD

**Issue by neuhalje** [corux/gitlab-omnibus-formula#1]
I was wondering why gpg-key checking is disabled in [runner.sls](https://github.com/corux/gitlab-formula/blob/master/gitlab/runner.sls#L8)? This seems like a  security issue

```yaml
gitlab-runner-repo:
  pkgrepo.managed:
    - humanname: runner_gitlab-ci-multi-runner
    - baseurl: https://packages.gitlab.com/runner/gitlab-ci-multi-runner/el/$releasever/$basearch
    - gpgcheck: 0   # <<<<< 
    - gpgkey: https://packages.gitlab.com/gpg.key
    - require:
      - cmd: gitlab-repo-key
```
